import type {
  Shipment,
  Route,
  RiskProfile,
  Customer,
  Disruption,
  MemoryEntry,
  Task,
  AgentRun,
  AuditLog,
  ToolCall,
} from "./types";

// Helpers to produce stable, realistic relative timestamps.
const HOUR = 3600 * 1000;
const now = Date.now();
const iso = (msAgo: number) => new Date(now - msAgo).toISOString();
const ahead = (msAhead: number) => new Date(now + msAhead).toISOString();

// ── Customers ───────────────────────────────────────────────────────────────
export const customers: Customer[] = [
  {
    id: "cust_nordretail",
    name: "NordRetail",
    serviceLevel: "gold",
    region: "Nordics",
    slaMaxDelayHours: 6,
    contactName: "Annika Lind",
    activeShipmentIds: ["ship_voyage_402", "ship_voyage_641"],
  },
  {
    id: "cust_arcticfoods",
    name: "ArcticFoods",
    serviceLevel: "platinum",
    region: "Nordics",
    slaMaxDelayHours: 4,
    contactName: "Henrik Sol",
    activeShipmentIds: ["ship_voyage_518", "ship_voyage_733"],
  },
  {
    id: "cust_medsupply",
    name: "MedSupply Continental",
    serviceLevel: "platinum",
    region: "DACH",
    slaMaxDelayHours: 3,
    contactName: "Dr. Lena Vogt",
    activeShipmentIds: ["ship_voyage_callisto"],
  },
  {
    id: "cust_continental",
    name: "Continental Parts Co.",
    serviceLevel: "silver",
    region: "Benelux",
    slaMaxDelayHours: 12,
    contactName: "Joost Bakker",
    activeShipmentIds: ["ship_voyage_889"],
  },
];

// ── Disruptions ─────────────────────────────────────────────────────────────
export const disruptions: Disruption[] = [
  {
    id: "disr_brenner_rockslide",
    name: "Brenner Pass Rockslide",
    type: "infrastructure",
    severity: "high",
    affectedRouteIds: ["route_brenner"],
    affectedZones: ["zone_eu_alpine"],
    reportedAt: iso(5 * HOUR),
    status: "active",
    summary:
      "Rockslide on the A22 Brenner corridor has reduced throughput to a single lane. Convoy escorts in effect; transit time materially extended.",
  },
  {
    id: "disr_rotterdam_port",
    name: "Rotterdam Port Disruption",
    type: "port_congestion",
    severity: "critical",
    affectedRouteIds: ["route_rotterdam_ruhr", "route_rotterdam_nordics"],
    affectedZones: ["zone_benelux_port"],
    reportedAt: iso(18 * HOUR),
    status: "active",
    summary:
      "Industrial action at Maasvlakte terminals has stalled container handling. Berth windows delayed 14–26h across deep-sea services.",
  },
  {
    id: "disr_alpine_weather",
    name: "Alpine Winter Advisory",
    type: "weather",
    severity: "moderate",
    affectedRouteIds: ["route_tauern"],
    affectedZones: ["zone_eu_alpine"],
    reportedAt: iso(2 * HOUR),
    status: "monitoring",
    summary:
      "Snowfall forecast above 1,400m. Chains advised; minor delays possible on alpine alternatives.",
  },
];

// ── Routes ──────────────────────────────────────────────────────────────────
export const routes: Route[] = [
  {
    id: "route_brenner",
    name: "Brenner Pass Corridor",
    origin: "Verona DC",
    destination: "Munich Hub",
    available: true, // degraded but technically open
    durationHours: 17, // extended by the rockslide (base 11h)
    zones: ["zone_eu_alpine", "zone_eu_core"],
    capacityUtilization: 0.94,
    temperatureControlled: true,
    activeDisruptionIds: ["disr_brenner_rockslide"],
    distanceKm: 415,
  },
  {
    id: "route_tauern",
    name: "Tauern Alternative Corridor",
    origin: "Verona DC",
    destination: "Munich Hub",
    available: true,
    durationHours: 14,
    zones: ["zone_eu_alpine", "zone_eu_core"],
    capacityUtilization: 0.71,
    temperatureControlled: true,
    activeDisruptionIds: ["disr_alpine_weather"],
    distanceKm: 468,
  },
  {
    id: "route_alpha",
    name: "Thermal Cargo Route Alpha",
    origin: "Hamburg Cold Hub",
    destination: "Oslo DC",
    available: true,
    durationHours: 9,
    zones: ["zone_eu_core", "zone_nordics"],
    capacityUtilization: 0.58,
    temperatureControlled: true,
    activeDisruptionIds: [],
    distanceKm: 612,
  },
  {
    id: "route_rotterdam_ruhr",
    name: "Rotterdam–Ruhr Express",
    origin: "Rotterdam Port",
    destination: "Duisburg Hub",
    available: false, // closed by port disruption
    durationHours: 6,
    zones: ["zone_benelux_port", "zone_eu_core"],
    capacityUtilization: 0.99,
    temperatureControlled: false,
    activeDisruptionIds: ["disr_rotterdam_port"],
    distanceKm: 230,
  },
  {
    id: "route_rotterdam_nordics",
    name: "Rotterdam–Nordics Feeder",
    origin: "Rotterdam Port",
    destination: "Gothenburg DC",
    available: false,
    durationHours: 22,
    zones: ["zone_benelux_port", "zone_nordics"],
    capacityUtilization: 0.97,
    temperatureControlled: true,
    activeDisruptionIds: ["disr_rotterdam_port"],
    distanceKm: 940,
  },
  {
    id: "route_baltic",
    name: "Baltic Land Bridge",
    origin: "Hamburg Cold Hub",
    destination: "Helsinki DC",
    available: true,
    durationHours: 19,
    zones: ["zone_eu_core", "zone_nordics"],
    capacityUtilization: 0.64,
    temperatureControlled: true,
    activeDisruptionIds: [],
    distanceKm: 1180,
  },
];

// ── Risk profiles (per route) ───────────────────────────────────────────────
export const riskProfiles: RiskProfile[] = [
  {
    routeId: "route_brenner",
    riskScore: 82,
    disruptionIndicators: ["Active rockslide", "Single-lane convoy", "94% capacity"],
    weatherIndicators: ["Clear", "Light wind"],
    trend: "deteriorating",
  },
  {
    routeId: "route_tauern",
    riskScore: 41,
    disruptionIndicators: ["Reroute volume +30%"],
    weatherIndicators: ["Snowfall above 1,400m", "Chains advised"],
    trend: "stable",
  },
  {
    routeId: "route_alpha",
    riskScore: 12,
    disruptionIndicators: [],
    weatherIndicators: ["Clear"],
    trend: "improving",
  },
  {
    routeId: "route_rotterdam_ruhr",
    riskScore: 95,
    disruptionIndicators: ["Terminal labor action", "Berth backlog"],
    weatherIndicators: ["Coastal wind 35kt"],
    trend: "deteriorating",
  },
  {
    routeId: "route_rotterdam_nordics",
    riskScore: 88,
    disruptionIndicators: ["Feeder backlog", "97% capacity"],
    weatherIndicators: ["North Sea swell"],
    trend: "deteriorating",
  },
  {
    routeId: "route_baltic",
    riskScore: 23,
    disruptionIndicators: [],
    weatherIndicators: ["Calm seas"],
    trend: "stable",
  },
];

// ── Shipments ───────────────────────────────────────────────────────────────
export const shipments: Shipment[] = [
  {
    id: "ship_voyage_402",
    name: "Voyage-402",
    customerId: "cust_nordretail",
    status: "in_transit",
    cargoType: "temperature_sensitive",
    originHub: "Verona DC",
    destinationHub: "Munich Hub",
    assignedRouteId: "route_brenner",
    eta: ahead(16 * HOUR),
    weightKg: 18400,
    unitsCount: 26,
    declaredValueEur: 412000,
    thermal: { maxTempC: 5, minTempC: 0 },
    currentTempC: 4,
    prohibitedZones: ["zone_restricted_mil"],
    maxTransitHours: 15,
    priority: "p1",
    lastUpdated: iso(0.4 * HOUR),
  },
  {
    id: "ship_voyage_518",
    name: "Voyage-518",
    customerId: "cust_arcticfoods",
    status: "in_transit",
    cargoType: "perishable",
    originHub: "Hamburg Cold Hub",
    destinationHub: "Oslo DC",
    assignedRouteId: "route_alpha",
    eta: ahead(7 * HOUR),
    weightKg: 21200,
    unitsCount: 33,
    declaredValueEur: 188000,
    thermal: { maxTempC: -18, minTempC: -24 },
    currentTempC: -19,
    prohibitedZones: [],
    maxTransitHours: 20,
    priority: "p1",
    lastUpdated: iso(0.2 * HOUR),
  },
  {
    id: "ship_voyage_641",
    name: "Voyage-641",
    customerId: "cust_nordretail",
    status: "delayed",
    cargoType: "standard",
    originHub: "Rotterdam Port",
    destinationHub: "Gothenburg DC",
    assignedRouteId: "route_rotterdam_nordics",
    eta: ahead(30 * HOUR),
    weightKg: 26000,
    unitsCount: 40,
    declaredValueEur: 96000,
    thermal: { maxTempC: null, minTempC: null },
    currentTempC: null,
    prohibitedZones: [],
    maxTransitHours: 28,
    priority: "p2",
    lastUpdated: iso(1.1 * HOUR),
  },
  {
    id: "ship_voyage_733",
    name: "Voyage-733",
    customerId: "cust_arcticfoods",
    status: "exception",
    cargoType: "temperature_sensitive",
    originHub: "Hamburg Cold Hub",
    destinationHub: "Helsinki DC",
    assignedRouteId: "route_baltic",
    eta: ahead(20 * HOUR),
    weightKg: 15600,
    unitsCount: 22,
    declaredValueEur: 240000,
    thermal: { maxTempC: 2, minTempC: -2 },
    currentTempC: 6, // breach — drives a thermal exception
    prohibitedZones: [],
    maxTransitHours: 24,
    priority: "p1",
    lastUpdated: iso(0.3 * HOUR),
  },
  {
    id: "ship_voyage_callisto",
    name: "Voyage-Callisto",
    customerId: "cust_medsupply",
    status: "in_transit",
    cargoType: "high_value",
    originHub: "Verona DC",
    destinationHub: "Munich Hub",
    assignedRouteId: "route_tauern",
    eta: ahead(13 * HOUR),
    weightKg: 8200,
    unitsCount: 12,
    declaredValueEur: 1250000,
    thermal: { maxTempC: 8, minTempC: 2 },
    currentTempC: 5,
    prohibitedZones: ["zone_restricted_mil"],
    maxTransitHours: 16,
    priority: "p1",
    lastUpdated: iso(0.6 * HOUR),
  },
  {
    id: "ship_voyage_889",
    name: "Voyage-889",
    customerId: "cust_continental",
    status: "at_hub",
    cargoType: "standard",
    originHub: "Rotterdam Port",
    destinationHub: "Duisburg Hub",
    assignedRouteId: "route_rotterdam_ruhr",
    eta: ahead(26 * HOUR),
    weightKg: 31000,
    unitsCount: 48,
    declaredValueEur: 142000,
    thermal: { maxTempC: null, minTempC: null },
    currentTempC: null,
    prohibitedZones: [],
    maxTransitHours: 10,
    priority: "p3",
    lastUpdated: iso(2.2 * HOUR),
  },
];

// ── Memory entries (operational knowledge) ──────────────────────────────────
export const memoryEntries: MemoryEntry[] = [
  {
    id: "mem_brenner_2024",
    title: "Brenner Pass rockslide — Q4 mitigation",
    incidentType: "infrastructure_disruption",
    context:
      "Previous Brenner corridor closure extended transit beyond cargo integrity limits for temperature-sensitive freight.",
    recommendation:
      "Reroute temperature-sensitive cargo via the Tauern Alternative Corridor and pre-book reefer slots. Notify gold/platinum customers proactively.",
    tags: ["brenner", "alpine", "reroute", "temperature_sensitive"],
    createdAt: iso(34 * 24 * HOUR),
    reuseCount: 4,
    signals: ["route_brenner", "zone_eu_alpine", "infrastructure", "temperature_sensitive"],
  },
  {
    id: "mem_rotterdam_labor",
    title: "Rotterdam labor action — feeder fallback",
    incidentType: "port_congestion",
    context:
      "Maasvlakte terminal stoppages historically cascade to Nordics feeders with 18–30h delays.",
    recommendation:
      "Shift Nordics-bound volume to the Baltic Land Bridge and stage buffer inventory at Hamburg Cold Hub.",
    tags: ["rotterdam", "port", "feeder", "nordics"],
    createdAt: iso(60 * 24 * HOUR),
    reuseCount: 2,
    signals: ["route_rotterdam_nordics", "zone_benelux_port", "port_congestion"],
  },
  {
    id: "mem_thermal_excursion",
    title: "Reefer thermal excursion playbook",
    incidentType: "thermal_breach",
    context:
      "Temperature-sensitive shipments exceeding their max threshold require immediate hold-and-inspect before continued transit.",
    recommendation:
      "Hold shipment at nearest cold hub, log excursion, and require quality sign-off before release. Do not auto-approve continuation.",
    tags: ["thermal", "reefer", "quality", "hold"],
    createdAt: iso(12 * 24 * HOUR),
    reuseCount: 6,
    signals: ["temperature_sensitive", "thermal_breach", "perishable"],
  },
];

// ── Seed operational history (so list views are populated) ──────────────────
export const seedTasks: Task[] = [
  {
    id: "task_seed_1",
    prompt: "Which shipments are affected by the Rotterdam port disruption?",
    status: "completed",
    createdAt: iso(3 * HOUR),
    createdBy: "C. Koskinen",
    agentRunId: "run_seed_1",
    summary: "Impact analysis · Rotterdam disruption",
  },
  {
    id: "task_seed_2",
    prompt: "Which deliveries violate thermal constraints today?",
    status: "completed",
    createdAt: iso(6 * HOUR),
    createdBy: "C. Koskinen",
    agentRunId: "run_seed_2",
    summary: "Constraint scan · thermal",
  },
  {
    id: "task_seed_3",
    prompt:
      "Evaluate whether Voyage-Callisto can transit the Tauern corridor within SLA.",
    status: "completed",
    createdAt: iso(9 * HOUR),
    createdBy: "M. Aalto",
    agentRunId: "run_seed_3",
    summary: "Route feasibility · Voyage-Callisto",
  },
];

export const seedAgentRuns: AgentRun[] = [
  {
    id: "run_seed_1",
    taskId: "task_seed_1",
    status: "completed",
    startedAt: iso(3 * HOUR),
    completedAt: iso(3 * HOUR - 3200),
    durationMs: 3200,
    steps: [],
  },
  {
    id: "run_seed_2",
    taskId: "task_seed_2",
    status: "completed",
    startedAt: iso(6 * HOUR),
    completedAt: iso(6 * HOUR - 2700),
    durationMs: 2700,
    steps: [],
  },
  {
    id: "run_seed_3",
    taskId: "task_seed_3",
    status: "completed",
    startedAt: iso(9 * HOUR),
    completedAt: iso(9 * HOUR - 2950),
    durationMs: 2950,
    steps: [],
  },
];

export const seedToolCalls: ToolCall[] = [
  {
    id: "tc_seed_1",
    runId: "run_seed_1",
    toolName: "customer_impact_service",
    input: { disruptionId: "disr_rotterdam_port" },
    output: { affectedCustomers: 2, affectedShipments: 3 },
    latencyMs: 240,
    status: "success",
    timestamp: iso(3 * HOUR),
  },
  {
    id: "tc_seed_2",
    runId: "run_seed_2",
    toolName: "shipment_service",
    input: { filter: "temperature_sensitive" },
    output: { breaches: 1 },
    latencyMs: 180,
    status: "success",
    timestamp: iso(6 * HOUR),
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: "audit_seed_1",
    timestamp: iso(3 * HOUR),
    event: "Task executed",
    action: "Impact analysis — Rotterdam disruption",
    outcome: "success",
    user: "C. Koskinen",
    taskId: "task_seed_1",
  },
  {
    id: "audit_seed_2",
    timestamp: iso(6 * HOUR),
    event: "Constraint validation",
    action: "Thermal scan flagged Voyage-733",
    outcome: "blocked",
    user: "C. Koskinen",
    taskId: "task_seed_2",
  },
  {
    id: "audit_seed_3",
    timestamp: iso(9 * HOUR),
    event: "Route approval",
    action: "Voyage-Callisto approved for Tauern corridor",
    outcome: "approved",
    user: "M. Aalto",
    taskId: "task_seed_3",
  },
  {
    id: "audit_seed_4",
    timestamp: iso(18 * HOUR),
    event: "Disruption ingested",
    action: "Rotterdam Port Disruption registered",
    outcome: "info",
    user: "system",
    taskId: null,
  },
];
